### ISSUE TITLE
Extension immediately goes into a crash loop in Chromium

### ISSUE THREAD

**Issue by 3rd-st-ninja** [Slashroot101/zillow-available-internet#1]
Extension crashes in Chromium with a warning and an error.

Warning: "Permission '**://\*.mapbox.com/\*' is unknown or URL pattern is malformed."

Error: "Uncaught (in promise) ReferenceError: document is not defined"
script.js:2
  const internetIdExists = document.getElementById('internetId');

What other info can I provide?

**Comment by Slashroot101** [comment]
I think, hopefully, what I just released may fix it for you. It is kind of a band aid, but let me know if it does not work.

**Comment by Slashroot101** [comment]
You can ignore the mapbox warning, that was me just testing the extension permissions.

**Comment by Slashroot101** [comment]
You will immediately see it show up in the tab when you click on a house. Albeit very ugly, it is a lot faster than constantly tab swapping, haha.

**Comment by 3rd-st-ninja** [comment]
It's working now.  This is pretty awesome.  Great work!
